"""empty message

Revision ID: 655efc522969
Revises: 11c0631609f4
Create Date: 2024-03-22 09:20:18.131666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655efc522969'
down_revision = '11c0631609f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['assemblyai_id'])

    with op.batch_alter_table('transcript_json', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['assemblyai_id'])
        batch_op.drop_constraint('transcript_json_assemblyai_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'transcript', ['assemblyai_id'], ['assemblyai_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_json', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transcript_json_assemblyai_id_fkey', 'transcript', ['assemblyai_id'], ['assemblyai_id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
