"""empty message

Revision ID: 85b342dfed1f
Revises: 
Create Date: 2024-02-19 16:30:12.079957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b342dfed1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)

    op.create_table('transcript',
    sa.Column('assemblyai_id', sa.String(), nullable=False),
    sa.Column('audio_file_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('transcription_status', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('assemblyai_id'),
    sa.UniqueConstraint('assemblyai_id')
    )
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_user_id'), ['user_id'], unique=False)

    op.create_table('transcript_json',
    sa.Column('json_content', sa.JSON(), nullable=False),
    sa.Column('assemblyai_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assemblyai_id'], ['transcript.assemblyai_id'], ),
    sa.PrimaryKeyConstraint('assemblyai_id'),
    sa.UniqueConstraint('assemblyai_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_json')
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_user_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_project_name'))

    op.drop_table('transcript')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_id'))

    op.drop_table('project')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
