"""empty message

Revision ID: 8b84b6ee27a5
Revises: 
Create Date: 2024-02-18 10:05:59.283226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8b84b6ee27a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_user_email')

    op.drop_table('project')
    op.drop_table('transcript_json')
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_project_name')
        batch_op.drop_index('ix_transcript_user_email')

    op.drop_table('transcript')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript',
    sa.Column('assemblyai_id', sa.VARCHAR(), nullable=False),
    sa.Column('audio_file_name', sa.VARCHAR(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('transcription_status', sa.VARCHAR(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['project.name'], ),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('assemblyai_id'),
    sa.UniqueConstraint('assemblyai_id')
    )
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_user_email', ['user_email'], unique=False)
        batch_op.create_index('ix_transcript_project_name', ['project_name'], unique=False)

    op.create_table('transcript_json',
    sa.Column('json_content', sqlite.JSON(), nullable=False),
    sa.Column('assemblyai_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['assemblyai_id'], ['transcript.assemblyai_id'], ),
    sa.PrimaryKeyConstraint('assemblyai_id'),
    sa.UniqueConstraint('assemblyai_id')
    )
    op.create_table('project',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('ix_project_user_email', ['user_email'], unique=False)

    op.create_table('user',
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
